name: sooq1alzour
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  curved_navigation_bar: ^0.3.3
  image_picker: ^0.6.7+3
  device_info:
  flutter_spinkit:
  carousel_pro: ^1.0.0
  carousel_slider: ^2.2.1
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  flutter_image_compress: ^0.7.0
  image_cropper:
  get_it: ^4.0.2
  flutter_local_notifications: ^1.4.4+2
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  photo_view:
  flutter_launcher_icons: ^0.7.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/logo_png.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran.ttf
    - family: DigitalDisplayRegular
      fonts:
        - asset: assets/fonts/DigitalDisplayRegular-ODEO.ttf
#    - family: TS Rotger Regular
#      fonts:
#        - asset: assets/fonts/ArbFONTS-TSRotger-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
